force-app/main/default/objects/Case/fields/ATM_Fee_in_Other_Currencies_Stamp__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_Other_Currencies_Stamp__c</fullName>
    <label>ATM Fee in Other Currencies Stamp</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Case/fields/Card_Replacement_Cost_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost_Stamp__c</fullName>
    <label>Card Replacement Cost Stamp</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cost_per_Calendar_Month_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month_Stamp__c</fullName>
    <label>Cost per Calendar Month Stamp</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ATM_Fee_in_Other_Currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_Other_Currencies__c</fullName>
    <formula>IF( AND( N26_Promotion__r.ATM_Fee_Discount__c&gt;0, Promotion_Start_Date__c &lt;= TODAY() , Promotion_End_Date__c &gt;= TODAY()),  N26_Product__r.ATM_Fee_in_Other_Currencies__c-N26_Product__r.ATM_Fee_in_Other_Currencies__c*N26_Promotion__r.ATM_Fee_Discount__c,
N26_Product__r.ATM_Fee_in_Other_Currencies__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ATM Fee in Other Currencies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <formula>IF( AND( N26_Promotion__r.Card_Replacement_Cost_Discount__c &gt;0,  Promotion_Start_Date__c &lt;= TODAY() , Promotion_End_Date__c &gt;= TODAY()), 

ROUND(N26_Product__r.Card_Replacement_Cost__c-N26_Product__r.Card_Replacement_Cost__c*N26_Promotion__r.Card_Replacement_Cost_Discount__c ,2),

N26_Product__r.Card_Replacement_Cost__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <formula>IF( AND(  N26_Promotion__r.Cost_per_Calendar_Month_Discount__c &gt;0, Promotion_Start_Date__c &lt;= TODAY() , Promotion_End_Date__c &gt;= TODAY()), 

ROUND(N26_Product__r.Cost_per_Calendar_Month__c-N26_Product__r.Cost_per_Calendar_Month__c*N26_Promotion__r.Cost_per_Calendar_Month_Discount__c ,2),

N26_Product__r.Cost_per_Calendar_Month__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/ATM_Fee_in_Other_Currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_Other_Currencies__c</fullName>
    <label>ATM Fee in Other Currencies</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <label>Cost per Calendar Month</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseTrigger_Test.cls
@IsTest
private with sharing class CaseTrigger_Test {

    private static final String ADMIN_PROFILE_NAME = 'System Administrator';
    
    @TestSetup
    static void setup(){
        TestHelper.createTestUser(true, ADMIN_PROFILE_NAME);
        List<Product__c> testProducts = TestHelper.createProducts(); //Created 2 Products
        TestHelper.createContacts(2, true, testProducts); //Created 4 Contacts
    }

    //Create new Cases and check if the stamp fields are populated with the related Contact product fields
    @isTest
    static void insertNewCases(){
        User testUser = [SELECT Id FROM User WHERE Profile.Name = :ADMIN_PROFILE_NAME LIMIT 1];
        List<Product__c> products = [SELECT Id, Product__c, Home_Country__c FROM Product__c];
        Map<Id, Contact> testContacts = new Map<Id, Contact>([SELECT Id, ATM_Fee_in_Other_Currencies__c, Cost_per_Calendar_Month__c, Card_Replacement_Cost__c FROM Contact]);
        List<Case> testCases = TestHelper.createCases(2, (List<Contact>) testContacts.values(), false); //To create 8 Cases

        Test.startTest();
        System.runAs(testUser){
            insert testCases;
        }
        Test.stopTest();

        List<Case> assertCases = [SELECT ContactId, ATM_Fee_in_Other_Currencies_Stamp__c, Card_Replacement_Cost_Stamp__c, Cost_per_Calendar_Month_Stamp__c FROM Case WHERE Id IN : testCases];
        System.Assert.areEqual(8, assertCases.size());
        For(Case assertCase : assertCases){
            Assert.areEqual(assertCase.ATM_Fee_in_Other_Currencies_Stamp__c, testContacts.get(assertCase.ContactId).ATM_Fee_in_Other_Currencies__c, 'ATM Fee Stamp is wrong');
            Assert.areEqual(assertCase.Card_Replacement_Cost_Stamp__c, testContacts.get(assertCase.ContactId).Card_Replacement_Cost__c, 'Card Replacement Cost Stamp is wrong');
            Assert.areEqual(assertCase.Cost_per_Calendar_Month_Stamp__c, testContacts.get(assertCase.ContactId).Cost_per_Calendar_Month__c, 'Cost Calendar Month Stamp is wrong');
        }

    }

}