force-app/main/default/objects/Case/fields/ATM_Fee_in_Other_Currencies_Stamp__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_Other_Currencies_Stamp__c</fullName>
    <label>ATM Fee in Other Currencies Stamp</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Case/fields/Card_Replacement_Cost_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost_Stamp__c</fullName>
    <label>Card Replacement Cost Stamp</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cost_per_Calendar_Month_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month_Stamp__c</fullName>
    <label>Cost per Calendar Month Stamp</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ATM_Fee_in_Other_Currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_Other_Currencies__c</fullName>
    <formula>IF( AND( N26_Promotion__r.ATM_Fee_Discount__c&gt;0, Promotion_Start_Date__c &lt;= TODAY() , Promotion_End_Date__c &gt;= TODAY()),  N26_Product__r.ATM_Fee_in_Other_Currencies__c-N26_Product__r.ATM_Fee_in_Other_Currencies__c*N26_Promotion__r.ATM_Fee_Discount__c,
N26_Product__r.ATM_Fee_in_Other_Currencies__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ATM Fee in Other Currencies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <formula>IF( AND( N26_Promotion__r.Card_Replacement_Cost_Discount__c &gt;0,  Promotion_Start_Date__c &lt;= TODAY() , Promotion_End_Date__c &gt;= TODAY()), 

ROUND(N26_Product__r.Card_Replacement_Cost__c-N26_Product__r.Card_Replacement_Cost__c*N26_Promotion__r.Card_Replacement_Cost_Discount__c ,2),

N26_Product__r.Card_Replacement_Cost__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <formula>IF( AND(  N26_Promotion__r.Cost_per_Calendar_Month_Discount__c &gt;0, Promotion_Start_Date__c &lt;= TODAY() , Promotion_End_Date__c &gt;= TODAY()), 

ROUND(N26_Product__r.Cost_per_Calendar_Month__c-N26_Product__r.Cost_per_Calendar_Month__c*N26_Promotion__r.Cost_per_Calendar_Month_Discount__c ,2),

N26_Product__r.Cost_per_Calendar_Month__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHelper.cls
public with sharing class CaseTriggerHelper {
    //Method to stamp the current Contact N26 Product info from the related Contact on the Case record stamp fields
    public static void stampN26ProductInfo(List<Case> newCases) {
        List<Id> contactIDs = new List<Id>();
        for (Case c : newCases) {
            contactIDs.add(c.ContactId);
        }
        if(contactIDs.IsEmpty()) return;
        Map<Id, Contact> contactMap = new Map<Id, Contact>([SELECT Id, ATM_Fee_in_Other_Currencies__c, Cost_per_Calendar_Month__c, Card_Replacement_Cost__c FROM Contact WHERE Id IN : contactIDs]);
        for(Case c : newCases){
            if(contactMap.containsKey(c.ContactId)){
                c.ATM_Fee_in_Other_Currencies_Stamp__c = contactMap.get(c.ContactId).ATM_Fee_in_Other_Currencies__c;
                c.Cost_per_Calendar_Month_Stamp__c = contactMap.get(c.ContactId).Cost_per_Calendar_Month__c;
                c.Card_Replacement_Cost_Stamp__c = contactMap.get(c.ContactId).Card_Replacement_Cost__c;
            }
        }
    }
}