force-app/main/default/objects/Contact/fields/ATM_Fee_in_Other_Currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_Other_Currencies__c</fullName>
    <formula>IF( AND( N26_Promotion__r.ATM_Fee_Discount__c&gt;0, Promotion_Start_Date__c &lt;= TODAY() , Promotion_End_Date__c &gt;= TODAY()),  N26_Product__r.ATM_Fee_in_Other_Currencies__c-N26_Product__r.ATM_Fee_in_Other_Currencies__c*N26_Promotion__r.ATM_Fee_Discount__c,
N26_Product__r.ATM_Fee_in_Other_Currencies__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ATM Fee in Other Currencies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <formula>IF( AND( N26_Promotion__r.Card_Replacement_Cost_Discount__c &gt;0,  Promotion_Start_Date__c &lt;= TODAY() , Promotion_End_Date__c &gt;= TODAY()), 

ROUND(N26_Product__r.Card_Replacement_Cost__c-N26_Product__r.Card_Replacement_Cost__c*N26_Promotion__r.Card_Replacement_Cost_Discount__c ,2),

N26_Product__r.Card_Replacement_Cost__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <formula>IF( AND(  N26_Promotion__r.Cost_per_Calendar_Month_Discount__c &gt;0, Promotion_Start_Date__c &lt;= TODAY() , Promotion_End_Date__c &gt;= TODAY()), 

ROUND(N26_Product__r.Cost_per_Calendar_Month__c-N26_Product__r.Cost_per_Calendar_Month__c*N26_Promotion__r.Cost_per_Calendar_Month_Discount__c ,2),

N26_Product__r.Cost_per_Calendar_Month__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/ATM_Fee_in_Other_Currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_Other_Currencies__c</fullName>
    <label>ATM Fee in Other Currencies</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <label>Cost per Calendar Month</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/N26ProductsCache.cls
public with sharing class N26ProductsCache implements Cache.CacheBuilder {
    //CacheBuilder interface implementation which returns a Map of N26 Product String Codes (Product+HomeCountry) and the N26 Product and cache them so that they don't need to get retrieved any time the Contact Trigger runs
    private Map<String, Product__c> getN26Products(){
        Map<String, Product__c> N26Products = new Map<String, Product__c>();
        For(Product__c n26Prod : [SELECT Id, Name, Home_Country__c, Product__c, ATM_Fee_in_Other_Currencies__c, Card_Replacement_Cost__c, Cost_per_Calendar_Month__c FROM Product__c WITH SYSTEM_MODE]){
            N26Products.put(n26Prod.Product__c + n26Prod.Home_Country__c, n26Prod);
        }
        return N26Products;
    }
    
    public Object doLoad(String key){
        Object obj;
        obj = (Map<String, Product__c>) getN26Products();
        return obj;
    }

}