force-app/main/default/objects/Contact/fields/N26_Promotion__c.field-meta.xml
<CustomField>
    <fullName>N26_Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>N26 Promotion</label>
    <referenceTo>N26_Promotion__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/N26_Promotion__c/N26_Promotion__c.object-meta.xml
<CustomObject>
    <label>N26 Promotion</label>
    <nameField>
        <label>N26 Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>N26 Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Promotion_Relationship__c/Product_Promotion_Relationship__c.object-meta.xml
<CustomObject>
    <label>Product Promotion Relationship</label>
    <nameField>
        <label>Product Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Promotion Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Promotion_Relationship__c/fields/N26_Promotion__c.field-meta.xml
<CustomField>
    <fullName>N26_Promotion__c</fullName>
    <label>N26 Promotion</label>
    <referenceTo>N26_Promotion__c</referenceTo>
    <relationshipLabel>Product Promotion Relationships</relationshipLabel>
    <relationshipName>Product_Promotion_Relationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Promotion_Relationship__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Promotion Relationships</relationshipLabel>
    <relationshipName>Product_Promotion_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/N26PromotionsCache.cls
public with sharing class N26PromotionsCache implements Cache.CacheBuilder {
    //CacheBuilder interface implementation which returns a Map of N26 Product IDs and their Active related Promotions and cache them so that they don't need to get retrieved any time the Contact trigger runs
    private Map<Id, List<N26_Promotion__c>> getN26Promotions(){
        Map<Id, List<N26_Promotion__c>> N26Promotions = new Map<Id, List<N26_Promotion__c>>();
        For(N26_Promotion__c promo : [SELECT Id, Type__c, (SELECT Product__r.Id FROM Product_Promotion_Relationships__r) FROM N26_Promotion__c WHERE Start_Date__c <= TODAY AND End_Date__c >= TODAY WITH SYSTEM_MODE]){
            For(Product_Promotion_Relationship__c productPromo : promo.Product_Promotion_Relationships__r){
                if (!N26Promotions.containsKey(productPromo.Product__r.Id)) {
                    N26Promotions.put(productPromo.Product__r.Id, new List<N26_Promotion__c>());
                }
                N26Promotions.get(productPromo.Product__r.Id).add(promo);
            }
        }
        return N26Promotions;
    }
    
    public Object doLoad(String key){
        Object obj;
        obj = (Map<Id, List<N26_Promotion__c>>) getN26Promotions();
        return obj;
    }

}